### ISSUE TITLE
useSwipe hook non-passive event listener

### ISSUE THREAD

**Issue by 0riga** [shinyj1991/react-fullpage#1]
Hi. I am new to frontend development and this is my first time writing an issue. Thanks for the package. I was wondering if it is possible to remove the warning: [Violation] Added non-passive event listener to a scroll-blocking 'touchstart', 'touchmove' event. Consider marking event handler as 'passive' to make the page more responsive. The warning refers to the useSwipe hook. Thank you.
![image](https://github.com/shinyj1991/react-fullpage/assets/70951126/06ff90de-a0b9-4d4e-8a41-dc9ca136526e)

**Comment by shinyj1991** [comment]
Hi @0riga , first of all thanks for using the package I made. As you requested, I distributed a version with the passive option added to the eventListener option. Please install a new version.

```
npm install @shinyongjun/react-fullpage@v1.3.3
```

**Comment by shinyj1991** [comment]
close
